# Generated by Django 6.0.3 on 2026-09-01 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="active",
        ),
    ]
