# Generated by Django 6.0.3 on 2026-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
