# Generated by Django 6.0.3 on 2026-08-07 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberscheduleconfig",
            name="schedule_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="schedule.scheduletype"
            ),
        ),
        migrations.AlterField(
            model_name="monthlyschedule",
            name="schedule_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="schedule.scheduletype"
            ),
        ),
    ]
