# Generated by Django 6.0.3 on 2026-05-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_lyrics_chordchart"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="youtube_link",
            field=models.URLField(blank=True, default=""),
        ),
    ]
