# Generated by Django 6.0.3 on 2026-08-07 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0003_song_youtube_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HymnalHistorySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("min_seconds_to_count", models.PositiveIntegerField(default=30)),
                ("collapse_window_minutes", models.PositiveIntegerField(default=10)),
                ("max_batch_size", models.PositiveIntegerField(default=200)),
                ("max_past_days", models.PositiveIntegerField(default=90)),
                ("future_tolerance_minutes", models.PositiveIntegerField(default=5)),
            ],
            options={
                "verbose_name": "hymnal history settings",
                "verbose_name_plural": "hymnal history settings",
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="hymnal_history_settings_singleton"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "service window",
                "verbose_name_plural": "service windows",
                "ordering": ["weekday", "start_time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="service_window_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                        name="service_window_weekday_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HymnalViewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("client_event_id", models.UUIDField(unique=True)),
                ("device_id", models.CharField(max_length=64)),
                ("viewed_at", models.DateTimeField(db_index=True)),
                ("duration_seconds", models.PositiveIntegerField()),
                ("app_version", models.CharField(blank=True, default="", max_length=32)),
                ("platform", models.CharField(blank=True, default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hymn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="view_events",
                        to="songs.hymn",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hymn_view_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "hymn view event",
                "verbose_name_plural": "hymn view events",
                "ordering": ["-viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["hymn", "device_id", "viewed_at"],
                        name="songs_hymna_hymn_id_d5fdcd_idx",
                    ),
                    models.Index(fields=["viewed_at"], name="songs_hymna_viewed__8b9ebe_idx"),
                ],
            },
        ),
    ]
