# Generated by Django 6.0.3 on 2026-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0004_hymnalhistorysettings_servicewindow_hymnalviewevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="hymnalhistorysettings",
            name="window_grace_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
