# Generated by Django 6.0.3 on 2026-08-07 19:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0006_seed_service_windows"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="servicewindow",
            name="service_window_end_after_start",
        ),
        migrations.RemoveConstraint(
            model_name="servicewindow",
            name="service_window_weekday_range",
        ),
        migrations.DeleteModel(
            name="ServiceWindow",
        ),
    ]
