"""Passive hymnal usage telemetry.

Separate from ``Played``: that model is the official Sunday repertoire, registered
manually by an admin and pointing at ``Song``. These models record what the
congregation actually opened in the app, and point at ``Hymn``.

Service windows now come from the shared catalogue in ``core.models.ChurchService``
(feature 007); this module no longer owns a copy.
"""

from django.conf import settings
from django.db import models
from django.db.models import Q

from features.songs.models.hymnal import Hymn


class HymnalViewEvent(models.Model):
    """One hymn view that the app counted as real."""

    # Generated by the app; the idempotency key that makes a retried sync converge.
    client_event_id = models.UUIDField(unique=True)
    hymn = models.ForeignKey(Hymn, on_delete=models.PROTECT, related_name="view_events")
    # Null means anonymous: most members use the hymnal without logging in.
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="hymn_view_events",
    )
    # Opaque per-install id. CharField, not UUIDField, so a future app release can
    # change the format without the backend rejecting the device.
    device_id = models.CharField(max_length=64)
    # When the hymn was viewed, as reported by the device — not when it synced.
    viewed_at = models.DateTimeField(db_index=True)
    # Stored as received. Never re-validated against min_seconds_to_count: that
    # threshold is enforced on the client, and buffered events may carry an older value.
    duration_seconds = models.PositiveIntegerField()
    app_version = models.CharField(max_length=32, blank=True, default="")
    platform = models.CharField(max_length=32, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-viewed_at"]
        verbose_name = "hymn view event"
        verbose_name_plural = "hymn view events"
        indexes = [
            # Collapse candidate lookup at ingest time.
            models.Index(fields=["hymn", "device_id", "viewed_at"]),
            models.Index(fields=["viewed_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.hymn.number} @ {self.viewed_at:%Y-%m-%d %H:%M}"


class HymnalHistorySettings(models.Model):
    """Collection settings an admin can tune without a deploy. Exactly one row."""

    min_seconds_to_count = models.PositiveIntegerField(default=30)
    collapse_window_minutes = models.PositiveIntegerField(default=10)
    max_batch_size = models.PositiveIntegerField(default=200)
    max_past_days = models.PositiveIntegerField(default=90)
    future_tolerance_minutes = models.PositiveIntegerField(default=5)
    # Services run long. A hymn sung past the scheduled end still belongs to that
    # service, so matching extends this far beyond end_time. Read-time only —
    # changing it re-interprets past history without rewriting any event.
    window_grace_minutes = models.PositiveIntegerField(default=30)

    class Meta:
        ordering = ["id"]
        verbose_name = "hymnal history settings"
        verbose_name_plural = "hymnal history settings"
        constraints = [
            # Enforced by the database so no code path — admin, shell, bulk_create —
            # can create a second row.
            models.CheckConstraint(condition=Q(id=1), name="hymnal_history_settings_singleton"),
        ]

    def __str__(self) -> str:
        return "Hymnal history settings"
